"""
EcoPulse - Urban Stream Health Platform
Pydantic Data Models & Validation Schemas
"""

from datetime import datetime
from typing import Optional, List, Literal
from pydantic import BaseModel, Field, ConfigDict


class StationTelemetry(BaseModel):
    """
    Time-series sensor telemetry data recorded at a monitoring station.
    """
    station_id: str = Field(..., description="Unique identifier for the monitoring station (e.g. ST-01)")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of the telemetry recording")
    ph: float = Field(..., ge=0.0, le=14.0, description="pH level (0-14)")
    dissolved_oxygen: float = Field(..., ge=0.0, le=20.0, description="Dissolved Oxygen level in mg/L")
    turbidity: float = Field(..., ge=0.0, le=500.0, description="Turbidity level in NTU")
    water_temperature: float = Field(..., ge=-10.0, le=50.0, description="Water temperature in degrees Celsius")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "station_id": "ST-03",
                "timestamp": "2026-09-25T16:00:00Z",
                "ph": 6.8,
                "dissolved_oxygen": 7.2,
                "turbidity": 12.5,
                "water_temperature": 18.5
            }
        }
    )


class StationMetadata(BaseModel):
    """
    Geospatial metadata and current operational status for a stream monitoring station.
    """
    station_id: str = Field(..., description="Unique station ID (e.g. ST-01)")
    name: str = Field(..., description="Human-readable station name")
    sector: str = Field(..., description="Basin sector or reach description")
    latitude: float = Field(..., description="Geographic latitude coordinate")
    longitude: float = Field(..., description="Geographic longitude coordinate")
    risk_status: Literal["SAFE", "CAUTION", "CRITICAL"] = Field(..., description="Automated risk status")
    health_score: float = Field(100.0, ge=0.0, le=100.0, description="Current calculated Water Quality Index score")
    latest_telemetry: Optional[StationTelemetry] = Field(None, description="Most recent telemetry snapshot")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "station_id": "ST-01",
                "name": "Station 01 • Upper Basin Reach",
                "sector": "North Headwaters",
                "latitude": 47.6200,
                "longitude": -122.3490,
                "risk_status": "SAFE",
                "health_score": 92.5
            }
        }
    )


class AlertModel(BaseModel):
    """
    Automated One Health alert generated by anomaly detection or rule triggers.
    """
    alert_id: str = Field(..., description="Unique alert identifier")
    station_id: str = Field(..., description="ID of the affected station")
    severity: Literal["critical", "caution", "info"] = Field(..., description="Alert severity level")
    message: str = Field(..., description="Detailed alert description and One Health briefing")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    resolved: bool = Field(False, description="Whether the alert has been acknowledged/resolved")
    risk_triggers: Optional[List[str]] = Field(default_factory=list, description="Specific metric triggers causing the alert")
    action_required: Optional[str] = Field(None, description="Recommended remediation or public health advisory action")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "alert_id": "ALT-1001",
                "station_id": "ST-03",
                "severity": "critical",
                "message": "High turbidity detected, 40% spike. Downstream agricultural runoff warning. IRRIGATION ADVISORY REQUIRED",
                "timestamp": "2026-09-25T16:30:00Z",
                "resolved": False,
                "risk_triggers": ["Turbidity > 45 NTU", "pH < 6.0"],
                "action_required": "Issue Downstream Advisory & Deploy Autonomous Hydro-Drone"
            }
        }
    )


class BasinSummary(BaseModel):
    """
    Global basin health summary aggregate metrics.
    """
    overall_score: float = Field(..., description="Average Basin Health Score (0-100)")
    trend_7d_percent: float = Field(..., description="7-day health trend percentage (+/-)")
    active_alerts_count: int = Field(..., description="Total active (unresolved) alerts")
    critical_alerts_count: int = Field(..., description="Active critical severity alerts")
    caution_alerts_count: int = Field(..., description="Active caution severity alerts")
    total_stations: int = Field(..., description="Total monitored stations")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Generated at timestamp")


class TelemetryIngestResponse(BaseModel):
    """
    Response returned after processing a telemetry ingestion request.
    """
    status: str
    telemetry: StationTelemetry
    wqi_score: float
    risk_status: Literal["SAFE", "CAUTION", "CRITICAL"]
    insight: str
    alert_generated: Optional[AlertModel] = None


class SurgeSimulationResponse(BaseModel):
    """
    Response returned when artificially triggering a pollution surge anomaly.
    """
    status: str
    station_id: str
    injected_metrics: StationTelemetry
    new_wqi_score: float
    new_risk_status: Literal["SAFE", "CAUTION", "CRITICAL"]
    generated_alert: AlertModel
    insight: str
